# ---------------- #
#   Main Configs https://mazhuang.org  #
# ---------------- #
baseurl:
url: https://pigpigletsgo.github.io/dou_note.github.io
date_format: "ordinal"
title: ä»£ç ä»“åº“-ç®—æ³•ç¬”è®°
subtitle: "ğŸ‘¾ğŸ‘¾ğŸ‘¾"
description: "ä»£ç ä»“åº“-ç®—æ³•ç¬”è®°"
keywords: ç®—æ³•ç®—æ³•ç®—æ³•!!!
timezone: Asia/Shanghai
encoding: "utf-8"
# é¡µé¢å·¦ä¸‹è§’æ˜¾ç¤ºçš„å¹´ä»½
since: 2023
# æºç ä»“åº“ï¼Œè¯·æ›¿æ¢æˆè‡ªå·±çš„
repository: PigPigLetsGo/dou_note.github.io
# å¯¹ css å’Œ js èµ„æºçš„ cdn åŠ é€Ÿé…ç½®
cdn:
    jsdelivr:
        enabled: true
# å¯é€‰ç»„ä»¶é…ç½®
components:
    # åˆ†äº«
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: true
        # qq,facebook
        hide-platforms: 
    # ä¸è’œå­è®¿é—®ç»Ÿè®¡
    busuanzi:
        enabled: true
        start_date: 2023-11-27
    # My Popular Repositories
    side_bar_repo:
        enabled: false
        limit: 5
    # æ–‡ç« å­—æ•°ç»Ÿè®¡
    word_count:
        enabled: true
    # é¡µé¢å³ä¸Šè§’ï¼Œä»¥åŠã€Œå…³äºã€é¡µé¢çš„äºŒç»´ç 
    # ä¿®æ”¹å›¾ç‰‡è¯·æ›¿æ¢ assets/images/qrcode.jpg
    qrcode:
        enabled: false
        image_alt: loading...
    # ç»´åŸºç´¢å¼•é¡µä½¿ç”¨å“ªç§è§†å›¾ï¼Œæ”¯æŒ åˆ—è¡¨ï¼ˆlistï¼‰/åˆ†ç±»ï¼ˆcateï¼‰
    wiki:
        view: cate
    # å›¾ç‰‡ç¯ç®±æ•ˆæœåŠŸèƒ½
    fancybox:
        enabled: true
# å‹ç¼©é¡µé¢å†…å®¹
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# ä»£ç é«˜äº®é£æ ¼ï¼Œæ”¯æŒçš„ theme åˆ—è¡¨è§ https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Dkx
organization: è¡Œæ˜Ÿ
organization_url: 
github_username: PigPigLetsGo
location: solar system
email: 1851644015@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: é¦–é¡µ

  -
    href: /categories/
    label: åˆ†ç±»

  -
    href: /archives/
    label: å½’æ¡£
    mobile-hidden: false

  -
    href: /open-source/
    label: å¼€æº
    mobile-hidden: false

  -
    href: /fragments/
    label: ç‰‡æ®µ

  -
    href: /wiki/
    label: ç»´åŸº

  -
    href: /links/
    label: é“¾æ¥
    mobile-hidden: false

  -
    href: /about/
    label: å…³äº

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 6
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!é‡è¦!!! è¯·ä¿®æ”¹ä¸‹é¢è¿™äº›ä¿¡æ¯ä¸ºä½ è‡ªå·±ç”³è¯·çš„
# !!!Important!!! Please modify infos below to yours
# disqus é…ç½®å‚è€ƒï¼šhttps://disqus.com
disqus:
    username: 
# gitment é…ç½®å‚è€ƒï¼šhttps://imsun.net/posts/gitment-introduction/
gitment:
    owner: PigPigLetsGo
    repo: Pinglun
    oauth:
        client_id: 94a6fea58c3357e65bac
        client_secret: 19b2f9d18fee765487cc4dd9df5c391f95c06fec
# gitalk é…ç½®å‚è€ƒï¼šhttps://github.com/gitalk/gitalk#install
gitalk:
    owner: PigPigLetsGo
    repo:  Pinglunqu
    clientID: 94a6fea58c3357e65bac
    clientSecret: 19b2f9d18fee765487cc4dd9df5c391f95c06fec
# utterances é…ç½®å‚è€ƒï¼šhttps://utteranc.es/
utterances:
    repo: PigPigLetsGo/Pinglunqu
# beaudar é…ç½®å‚è€ƒï¼šhttps://beaudar.lipk.org/
beaudar:
    repo: PigPigLetsGo/Pinglunqu
# giscus é…ç½®å‚è€ƒï¼šhttps://giscus.app/zh-CN
giscus:
    repo: PigPigLetsGo/Pinglun
    repo-id: R_kgDOK9_qWQ
    category: Announcements
    category-id: DIC_kwDOK9_qWc4CcA4a
# åœ¨ä½¿ç”¨å…¶å®ƒè¯„è®ºç»„ä»¶æ—¶å¯ç‚¹å‡»æ˜¾ç¤º Disqus
lazy_load_disqus : true

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # æ˜¯å¦æ”¯æŒå…¨æ–‡æœç´¢
    fulltext: true
    # æœ€å¤šæ˜¾ç¤ºå¤šå°‘æ¡æœç´¢ç»“æœ
    limit: 6

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: false
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false
